apiVersion: v1
kind: Pod
metadata:
 name: springboot-configmap
 labels:
  app: springboot-configmap
  type: rest_service
spec:
 containers:
  - name: springboot-configmap
    image: raghuram04/springboot_configmap
    ports:
    - name: spring-port
      containerPort: 80
    env:
     - name: CONFIGENV
       valueFrom:
        configMapKeyRef:
          name: env-name
          key: configenv