apiVersion: v1
kind: Service
metadata:
 name: configmap-service
spec:
 type: NodePort
 ports:
  - targetPort: 8085
    nodePort: 30018
    port: 8085
 selector:
  app: springboot-configmap
  type: rest_service

